/**:
  ros__parameters:
    # YOLOv8模型参数
    weight_path: "yolov8n.pt"  # 模型权重文件路径
    conf: 0.5                  # 置信度阈值
    visualize: true            # 是否显示可视化窗口
    
    # ROS话题参数
    image_topic: "/camera/camera/image_raw"  # 输入图像话题
    pub_topic: "/yolov8/BoundingBoxes"      # 输出边界框话题
    
    # 相机参数
    camera_frame: "camera_color_optical_frame"  # 相机坐标系名称
    
    # 硬件参数
    use_cpu: false  # 是否使用CPU进行推理（true表示使用CPU，false表示使用GPU）